window.RECIPES = [
{id:'pommes',name:'Extra knusprige Pommes',country:'Amerikanisch',type:'Beilage',time:24,servings:4,desc:'Goldbraune Airfryer-Pommes mit wenig Öl und richtigem Crunch.',tags:['Kinderliebling','Schnell','Knusprig'],ingredients:[['Kartoffeln',800,'g'],['Öl',1,'EL'],['Salz',1,'TL'],['Paprika edelsüß',1,'TL']],steps:['Kartoffeln schneiden und 20 Minuten wässern.','Sehr gut trocknen, mit Öl und Gewürzen mischen.','Bei 200 °C ca. 22–24 Minuten airfryen und zwischendurch schütteln.']},
{id:'nuggets',name:'Chicken Nuggets Familienportion',country:'Amerikanisch',type:'Hauptgericht',time:18,servings:4,desc:'Schnelle Nuggets, außen knusprig und innen saftig.',tags:['Familie','Kids','Schnell'],ingredients:[['Chicken Nuggets',800,'g'],['Pommesgewürz',1,'TL'],['Dip nach Wahl',4,'EL']],steps:['Nuggets locker in den Korb legen.','Bei 200 °C 16–18 Minuten garen.','Nach der Hälfte wenden oder schütteln.']},
{id:'meatballs',name:'Italienische Meatballs',country:'Italienisch',type:'Hauptgericht',time:28,servings:4,desc:'Saftige Hackbällchen mit Parmesan, Kräutern und Tomatensauce.',tags:['Italien','Meal Prep','Herzhaft'],ingredients:[['Rinderhack',500,'g'],['Parmesan',50,'g'],['Ei',1,'Stk.'],['Semmelbrösel',50,'g'],['Tomatensauce',400,'ml']],steps:['Hack mit Ei, Parmesan und Bröseln vermengen.','Bällchen formen und bei 190 °C 14 Minuten garen.','Mit Tomatensauce servieren.']},
{id:'bruschetta',name:'Mediterrane Bruschetta Bites',country:'Mediterran',type:'Snack',time:12,servings:4,desc:'Knusprige Brotscheiben mit Tomaten, Knoblauch und Basilikum.',tags:['Snack','Sommer','Vegetarisch'],ingredients:[['Baguette',1,'Stk.'],['Tomaten',300,'g'],['Olivenöl',2,'EL'],['Knoblauchzehe',1,'Stk.'],['Basilikum',1,'Handvoll']],steps:['Baguette schneiden und mit wenig Öl bestreichen.','Bei 180 °C 5–6 Minuten rösten.','Tomatenmix daraufgeben und direkt servieren.']},
{id:'spanish-potatoes',name:'Spanische Patatas Bravas',country:'Spanisch',type:'Beilage',time:30,servings:4,desc:'Würzige Kartoffelwürfel mit rauchiger Paprika und Aioli.',tags:['Tapas','Knusprig','Vegetarisch'],ingredients:[['Kartoffeln',900,'g'],['Olivenöl',2,'EL'],['Geräuchertes Paprikapulver',1,'TL'],['Aioli',120,'g']],steps:['Kartoffeln würfeln, würzen und ölen.','Bei 200 °C 25–30 Minuten garen.','Mit Aioli servieren.']},
{id:'salmon',name:'Zitronen-Lachs aus dem Airfryer',country:'Mediterran',type:'Hauptgericht',time:16,servings:2,desc:'Saftiger Lachs mit Zitrone, Kräutern und wenig Aufwand.',tags:['Fisch','Low Carb','Schnell'],ingredients:[['Lachsfilets',2,'Stk.'],['Zitrone',1,'Stk.'],['Olivenöl',1,'EL'],['Dill',1,'EL']],steps:['Lachs würzen und mit Zitrone belegen.','Bei 180 °C 12–16 Minuten garen.','Mit Salat oder Kartoffeln servieren.']},
{id:'quesadilla',name:'Chicken Quesadillas',country:'Mexikanisch',type:'Snack',time:14,servings:4,desc:'Knusprige Tortillas mit Hähnchen, Käse und Paprika.',tags:['Fingerfood','Schnell','Familie'],ingredients:[['Tortillas',4,'Stk.'],['Hähnchen gegart',300,'g'],['Käse gerieben',200,'g'],['Paprika',1,'Stk.']],steps:['Tortillas füllen und zusammenklappen.','Bei 190 °C 8–10 Minuten backen.','In Stücke schneiden.']},
{id:'veggie-pasta-bake',name:'Italienischer Pasta-Auflauf',country:'Italienisch',type:'Hauptgericht',time:35,servings:4,desc:'Cremiger Pasta-Auflauf mit Gemüse und Mozzarella.',tags:['Vegetarisch','Ofenstyle','Familie'],ingredients:[['Pasta vorgekocht',500,'g'],['Tomatensauce',400,'ml'],['Mozzarella',200,'g'],['Zucchini',1,'Stk.']],steps:['Alles in eine passende Form geben.','Mit Mozzarella bestreuen.','Bei 180 °C ca. 25–35 Minuten garen.']},
{id:'bbq-wings',name:'BBQ Chicken Wings',country:'Amerikanisch',type:'Hauptgericht',time:32,servings:4,desc:'Würzige Wings mit klebriger BBQ-Glasur.',tags:['BBQ','Party','Knusprig'],ingredients:[['Chicken Wings',1000,'g'],['BBQ Sauce',120,'ml'],['Paprika',1,'TL'],['Salz',1,'TL']],steps:['Wings würzen.','Bei 190 °C 25 Minuten garen.','Mit BBQ Sauce glasieren und weitere 5–7 Minuten garen.']},
{id:'garlic-shrimp',name:'Knoblauch-Garnelen',country:'Spanisch',type:'Snack',time:10,servings:2,desc:'Schnelle Gambas mit Knoblauch, Zitrone und Petersilie.',tags:['Tapas','Fisch','Schnell'],ingredients:[['Garnelen',300,'g'],['Knoblauchzehen',2,'Stk.'],['Olivenöl',1,'EL'],['Zitrone',0.5,'Stk.']],steps:['Garnelen marinieren.','Bei 190 °C 7–10 Minuten garen.','Mit Zitrone beträufeln.']}
];
