const recipes = Array.isArray(window.RECIPES) ? window.RECIPES : [];
const els = {
 grid: document.querySelector('#recipeGrid'), empty: document.querySelector('#emptyState'), search: document.querySelector('#searchInput'), country: document.querySelector('#countryFilter'), type: document.querySelector('#typeFilter'), time: document.querySelector('#timeFilter'), reset: document.querySelector('#resetFilters'), recipeCount: document.querySelector('#recipeCount'), favoriteCount: document.querySelector('#favoriteCount'), shoppingCount: document.querySelector('#shoppingCount'), shoppingList: document.querySelector('#shoppingList'), clearShopping: document.querySelector('#clearShopping'), viewButtons: document.querySelectorAll('.view-btn'), showFavoritesTop: document.querySelector('#showFavoritesTop')
};
const recipeIds = new Set(recipes.map(r=>r.id));
let favorites = loadArray('ninjaFavoritesV2').filter(id=>recipeIds.has(id));
let shopping = loadObj('ninjaShoppingV2');
let view = 'all';
function loadArray(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return []}}
function loadObj(k){try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}}
function save(){localStorage.setItem('ninjaFavoritesV2',JSON.stringify(favorites));localStorage.setItem('ninjaShoppingV2',JSON.stringify(shopping));}
function setupFilters(){fillSelect(els.country,'Alle Länder',[...new Set(recipes.map(r=>r.country))].sort());fillSelect(els.type,'Alle Speisen',[...new Set(recipes.map(r=>r.type))].sort());}
function fillSelect(el,label,items){el.innerHTML=`<option value="all">${label}</option>`+items.map(i=>`<option value="${i}">${i}</option>`).join('');}
function filtered(){const q=els.search.value.trim().toLowerCase();return recipes.filter(r=>{if(view==='favorites'&&!favorites.includes(r.id))return false;if(q&&!`${r.name} ${r.desc} ${r.tags.join(' ')}`.toLowerCase().includes(q))return false;if(els.country.value!=='all'&&r.country!==els.country.value)return false;if(els.type.value!=='all'&&r.type!==els.type.value)return false;if(els.time.value!=='all'&&r.time>Number(els.time.value))return false;return true;});}
function render(){const list=filtered();els.recipeCount.textContent=recipes.length;els.favoriteCount.textContent=favorites.length;updateShopping();els.grid.innerHTML=list.map(card).join('');els.empty.hidden=list.length!==0;els.empty.textContent=view==='favorites'?'Noch keine Favoriten vorhanden. Klicke bei einem Rezept auf das Herz.':'Keine Rezepte gefunden.';bindCards();save();}
function card(r){const fav=favorites.includes(r.id);const checked=!!shopping[r.id];const portions=shopping[r.id]?.portions||r.servings;return `<article class="card"><div class="card__top"><div><div class="meta">${r.country} · ${r.type} · ${r.time} Min.</div><h3>${r.name}</h3></div><button class="fav ${fav?'is-active':''}" data-fav="${r.id}" aria-label="Favorit">${fav?'♥':'♡'}</button></div><p>${r.desc}</p><div class="tags">${r.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><details class="details"><summary>Zubereitung & Zutaten anzeigen</summary><h4>Zutaten für ${r.servings} Portionen</h4><ul>${r.ingredients.map(i=>`<li>${i[0]} – ${i[1]} ${i[2]}</li>`).join('')}</ul><h4>Zubereitung</h4><ol>${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol></details><label class="shop-row"><input type="checkbox" data-shop="${r.id}" ${checked?'checked':''}> Auf die Einkaufsliste setzen</label><label class="portion">Portionen <input type="number" min="1" max="12" value="${portions}" data-portion="${r.id}"></label></article>`;}
function bindCards(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>{const id=b.dataset.fav;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];render();});document.querySelectorAll('[data-shop]').forEach(c=>c.onchange=()=>{const id=c.dataset.shop;const r=recipes.find(x=>x.id===id);if(c.checked)shopping[id]={portions:r.servings};else delete shopping[id];render();});document.querySelectorAll('[data-portion]').forEach(i=>i.oninput=()=>{const id=i.dataset.portion;if(shopping[id]){shopping[id].portions=Math.max(1,Number(i.value)||1);updateShopping();save();}});}
function updateShopping(){const totals={};Object.entries(shopping).forEach(([id,item])=>{const r=recipes.find(x=>x.id===id);if(!r)return;const factor=(item.portions||r.servings)/r.servings;r.ingredients.forEach(([name,amount,unit])=>{const key=name+'|'+unit;totals[key]=(totals[key]||0)+amount*factor;});});const entries=Object.entries(totals);els.shoppingCount.textContent=entries.length;els.shoppingList.innerHTML=entries.length?entries.map(([key,val])=>{const [name,unit]=key.split('|');const n=Math.round(val*10)/10;return `<div class="shopping-item"><strong>${name}</strong><span>${n} ${unit}</span></div>`;}).join(''):'<p class="empty">Noch keine Zutaten in der Einkaufsliste.</p>';}
['input','change'].forEach(evt=>{els.search.addEventListener(evt,render);els.country.addEventListener(evt,render);els.type.addEventListener(evt,render);els.time.addEventListener(evt,render);});
els.reset.onclick=()=>{els.search.value='';els.country.value='all';els.type.value='all';els.time.value='all';render();};
els.clearShopping.onclick=()=>{shopping={};render();};
els.viewButtons.forEach(b=>b.onclick=()=>{view=b.dataset.view;els.viewButtons.forEach(x=>x.classList.toggle('is-active',x===b));if(view==='shopping')document.querySelector('#shopping').scrollIntoView({behavior:'smooth'});render();});
els.showFavoritesTop.onclick=()=>{view='favorites';els.viewButtons.forEach(x=>x.classList.toggle('is-active',x.dataset.view==='favorites'));document.querySelector('#recipes').scrollIntoView({behavior:'smooth'});render();};
setupFilters();render();
